server:
  port: 9999
spring:
  config:
#    import: /opt/p6e/console/p6e-console-application.yml
    import: D:\\env\p6e-coat-file-application.yml
  jpa:
    open-in-view: false
    properties:
      hibernate:
        show_sql: true
        format_sql: true
logging:
  config: 'classpath:p6e-coat-logback.xml'

